name: Test/Analyse

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  call-install-deps:
    uses: ./.github/workflows/install-deps.yml
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    needs: call-install-deps

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: cs2pr

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Cache
        uses: actions/cache@v4
        with:
          path: |
            vendor
          key: composer--${{ hashFiles('composer.lock') }}
          fail-on-cache-miss: true
        id: cache

      - name: PHPSTAN
        run: composer run phpstan:ci

      - name: PHPCS
        id: phpcs
        continue-on-error: true
        run: composer run phpcs:ci

      - name: Show PHPCS results in PR
        if: ${{ always() && steps.phpcs.outcome == 'failure' }}
        run: cs2pr ./phpcs-report.xml --graceful-warnings

      - name: PHP Unit Test
        run: composer run test:unit