name: Test/Analyse

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  pull_request:

jobs:
  call-install-deps:
    uses: ./.github/workflows/install-deps.yml
    secrets: inherit

  test:
    runs-on: ubuntu-latest
    needs: call-install-deps

    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'

      - name: Checkout
        uses: actions/checkout@v4

      - name: Load Cache
        uses: actions/cache@v4
        with:
          path: |
            vendor
          key: composer--${{ hashFiles('composer.lock') }}
          fail-on-cache-miss: true
        id: cache

      - name: Static Analyse
        run: composer run test:static

      - name: PHP Unit Test
        run: composer run test:unit